import React, { useState } from 'react';

const App = () => {
  const [startupIdea, setStartupIdea] = useState('');
  const [roadmap, setRoadmap] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  // A more robust Markdown-to-HTML parser
  const parseMarkdown = (text) => {
    if (!text) return { __html: '' };
    
    // Replace markdown headers with appropriate HTML tags
    let html = text.replace(/^### (.*$)/gmi, '<h3 class="text-xl font-bold mt-6 mb-2 text-purple-400">$1</h3>');
    html = html.replace(/^## (.*$)/gmi, '<h2 class="text-2xl font-bold mt-8 mb-4 text-blue-400">$1</h2>');
    
    // Replace bold markdown with strong tags
    html = html.replace(/\*\*(.*?)\*\*/gmi, '<strong>$1</strong>');
    
    // Replace bullet points with an unordered list
    html = html.replace(/^- (.*$)/gmi, '<li>$1</li>');
    html = html.replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>');
    
    // Replace newlines with breaks
    html = html.replace(/\n/g, '<br/>');

    // Remove any remaining <br/> tags inside list items to prevent double spacing
    html = html.replace(/<li>(.*?)<br\/>/g, '<li>$1');

    return { __html: html };
  };

  const handleGenerateRoadmap = async () => {
    if (!startupIdea.trim()) {
      alert('Please enter your startup idea.');
      return;
    }

    setIsLoading(true);
    setRoadmap('');

    // Call your local server endpoint instead of the Gemini API directly
    const localApiUrl = '/generate-roadmap'; 

    let retries = 3;
    while (retries > 0) {
      try {
        const response = await fetch(localApiUrl, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ idea: startupIdea }),
        });

        if (!response.ok) {
          throw new Error(`Server call failed with status: ${response.status}`);
        }

        const result = await response.json();
        const generatedText = result.roadmap; // Assuming your server returns the roadmap in a 'roadmap' field

        if (generatedText) {
          setRoadmap(generatedText);
          break; // Success, exit the loop
        } else {
          throw new Error('No content generated by the server.');
        }
      } catch (error) {
        console.error('Error fetching data from server:', error);
        retries--;
        if (retries === 0) {
          setRoadmap(`An error occurred while generating the roadmap. Please try again. Error: ${error.message}`);
        }
      }
    }

    setIsLoading(false);
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen p-4 bg-gray-950 text-white font-inter">
      {/* Hero Section */}
      <section className="text-center py-20 px-4 max-w-4xl w-full">
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500 mb-4 animate-fade-in-up">
          Turn Your Idea Into a Strategic Roadmap
        </h1>
        <p className="text-gray-300 text-lg sm:text-xl max-w-2xl mx-auto mb-8 animate-fade-in-up delay-200">
          Describe your startup idea and get an AI-generated roadmap with market analysis, competitive insights, and step-by-step execution plan.
        </p>
      </section>

      {/* Idea Input Form */}
      <section className="w-full max-w-3xl mb-12 animate-fade-in-up delay-400">
        <div className="card-gradient p-6 sm:p-8 rounded-3xl shadow-lg border border-gray-700/50">
          <label htmlFor="startup-idea" className="flex items-center text-sm font-medium text-gray-400 mb-4">
            <span className="bg-gray-800 text-purple-400 rounded-full w-6 h-6 flex items-center justify-center mr-2">💡</span>
            Describe Your Startup Idea
          </label>
          <textarea
            id="startup-idea"
            rows="6"
            className="w-full p-4 text-sm bg-gray-900 text-white rounded-xl resize-none outline-none focus:ring-2 focus:ring-purple-500 transition-all duration-300 placeholder-gray-500"
            placeholder="e.g., A mobile app that uses AI to help people discover and book unique local experiences based on their interests, budget, and location..."
            value={startupIdea}
            onChange={(e) => setStartupIdea(e.target.value)}
            disabled={isLoading}
          />
          <div className="flex justify-between items-center mt-2 text-xs text-gray-500">
            <span>{startupIdea.length}/2000 characters</span>
            <span>Be detailed for better insights</span>
          </div>
          <div className="mt-6 flex justify-center">
            <button
              onClick={handleGenerateRoadmap}
              disabled={isLoading}
              className="btn-hero px-12 py-4 rounded-xl text-lg font-semibold flex items-center justify-center transition-all duration-300"
            >
              {isLoading ? (
                <div className="flex items-center">
                  <svg className="animate-spin h-5 w-5 mr-3 text-white" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Generating...
                </div>
              ) : (
                <>
                  Generate AI Roadmap
                  <span className="ml-2">✨</span>
                </>
              )}
            </button>
          </div>
        </div>
      </section>

      {/* Roadmap Output */}
      {roadmap && (
        <section className="w-full max-w-3xl mb-12 animate-fade-in-up delay-600">
          <div className="bg-gray-800 p-6 sm:p-8 rounded-3xl shadow-xl border border-gray-700">
            <h2 className="text-xl sm:text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400 mb-4">Your Strategic Roadmap</h2>
            <div
              className="prose prose-invert max-w-none text-gray-300 leading-relaxed"
              dangerouslySetInnerHTML={parseMarkdown(roadmap)}
            ></div>
          </div>
        </section>
      )}
    </div>
  );
};

export default App;
